### ISSUE TITLE
feat: add swerve subsystem

### ISSUE THREAD

**Issue by TheGamer1002** [Bearbots6964/FRC2024#13]
Using [YAGSL](https://github.com/BroncBotz3481/YAGSL) for our swerve library. Currently waiting on their 2024 release.

```[tasklist]
### Tasks
- [x] Wait for 2024 release
- [x] Add vendordep
- [ ] Configure for MAXSwerve
- [ ] Integrate other subsystems
```

**Comment by NyxAlexandra** [comment]
IIRC they have already updated for 2024, just haven't created the latest release. can't we just use the main branch instead of the latest release until that is released?

**Comment by NyxAlexandra** [comment]
also, was there a discussion regarding maxSWERVE versus YGSL? (I have no preference personally)

**Comment by TheGamer1002** [comment]
> IIRC they have already updated for 2024, just haven't created the latest release. can't we just use the main branch instead of the latest release until that is released?

I'd personally like to use a vendordep, because it can receive updates. I don't want to just pull off of main because there hasn't officially been a release (which means there may be bugs).

**Comment by NyxAlexandra** [comment]
think this is done?
